-- Run this once in Supabase > SQL Editor before using Remove Inventory / Sold.

create table if not exists public.inventory_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  pid bigint not null,
  name text not null,
  event_type text not null check (event_type in ('remove','sold')),
  qty integer not null check (qty > 0),
  sold_price numeric check (sold_price is null or sold_price >= 0),
  date date not null default current_date,
  created_at timestamptz not null default now(),
  constraint sold_price_required check (
    (event_type = 'remove' and sold_price is null) or
    (event_type = 'sold' and sold_price is not null)
  )
);

alter table public.inventory_events enable row level security;

drop policy if exists "inventory_events_select_own" on public.inventory_events;
create policy "inventory_events_select_own"
on public.inventory_events for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "inventory_events_insert_own" on public.inventory_events;
create policy "inventory_events_insert_own"
on public.inventory_events for insert
to authenticated
with check (auth.uid() = user_id);

create index if not exists inventory_events_user_pid_date_idx
on public.inventory_events (user_id, pid, date, id);
